import { Book } from "./types";

export const INITIAL_BOOKS: Book[] = [
  {
    id: "1",
    title: "Atomic Habits",
    author: "James Clear",
    coverUrl: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&q=80&w=600",
    shelf: "reading",
    rating: 5,
    currentPage: 182,
    totalPages: 320,
    dateAdded: "2026-09-10",
    genre: "Self-Help",
    isFavorite: true,
    description: "An easy & proven way to build good habits & break bad ones.",
  },
  {
    id: "2",
    title: "Project Hail Mary",
    author: "Andy Weir",
    coverUrl: "https://images.unsplash.com/photo-1532012164546-f432f2e3777f?auto=format&fit=crop&q=80&w=600",
    shelf: "reading",
    rating: 5,
    currentPage: 290,
    totalPages: 496,
    dateAdded: "2026-09-15",
    genre: "Sci-Fi",
    isFavorite: true,
    description: "A lone astronaut must save the earth from disaster.",
  },
  {
    id: "3",
    title: "Clean Architecture",
    author: "Robert C. Martin",
    coverUrl: "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&q=80&w=600",
    shelf: "want_to_read",
    rating: 0,
    currentPage: 0,
    totalPages: 432,
    dateAdded: "2026-09-20",
    genre: "Technology",
    isFavorite: false,
    description: "A craftsman's guide to software structure and design.",
  },
  {
    id: "4",
    title: "Designing Data-Intensive Applications",
    author: "Martin Kleppmann",
    coverUrl: "https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?auto=format&fit=crop&q=80&w=600",
    shelf: "want_to_read",
    rating: 0,
    currentPage: 0,
    totalPages: 616,
    dateAdded: "2026-09-22",
    genre: "Technology",
    isFavorite: true,
    description: "The big ideas behind reliable, scalable, and maintainable systems.",
  },
  {
    id: "5",
    title: "The Psychology of Money",
    author: "Morgan Housel",
    coverUrl: "https://images.unsplash.com/photo-1592496431122-2349e0fbc666?auto=format&fit=crop&q=80&w=600",
    shelf: "completed",
    rating: 5,
    currentPage: 256,
    totalPages: 256,
    dateAdded: "2026-08-01",
    genre: "Finance",
    isFavorite: true,
    description: "Timeless lessons on wealth, greed, and happiness.",
  },
  {
    id: "6",
    title: "Deep Work",
    author: "Cal Newport",
    coverUrl: "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&q=80&w=600",
    shelf: "completed",
    rating: 4,
    currentPage: 304,
    totalPages: 304,
    dateAdded: "2026-08-14",
    genre: "Productivity",
    isFavorite: false,
    description: "Rules for focused success in a distracted world.",
  },
  {
    id: "7",
    title: "Dune",
    author: "Frank Herbert",
    coverUrl: "https://images.unsplash.com/photo-1506880018603-83d5b814b5a6?auto=format&fit=crop&q=80&w=600",
    shelf: "completed",
    rating: 5,
    currentPage: 688,
    totalPages: 688,
    dateAdded: "2026-07-20",
    genre: "Sci-Fi",
    isFavorite: true,
    description: "Set on the desert planet Arrakis, Dune tells the story of Paul Atreides.",
  },
];
