export const Colors = {
  primary: "#2563EB",
  primaryLight: "#EFF6FF",
  secondary: "#4F46E5",
  background: "#F8FAFC",
  card: "#FFFFFF",
  text: "#0F172A",
  textSecondary: "#64748B",
  textMuted: "#94A3B8",
  border: "#E2E8F0",
  success: "#10B981",
  warning: "#F59E0B",
  danger: "#EF4444",
  star: "#FBBF24",
  shelves: {
    reading: {
      bg: "#ECFDF5",
      text: "#065F46",
      border: "#A7F3D0",
      label: "Reading",
    },
    want_to_read: {
      bg: "#EFF6FF",
      text: "#1E40AF",
      border: "#BFDBFE",
      label: "Want to Read",
    },
    completed: {
      bg: "#FEF3C7",
      text: "#92400E",
      border: "#FDE68A",
      label: "Completed",
    },
    favorites: {
      bg: "#FDF2F8",
      text: "#9D174D",
      border: "#FBCFE8",
      label: "Favorites",
    },
  },
};
